[package]
name = 'aptos-hello-world'
version = '1.0.0'


[addresses]
Std = "0x1"
aptos_std = "0x1"

[dependencies]
AptosFramework = { local = "D:/aptos-core/aptos-core/aptos-move/framework/aptos-framework"}